export default Object.freeze({
  OIDC_AUTHORITY: process.env.OIDC_AUTHORITY,
  OIDC_CLIENT_ID: process.env.OIDC_CLIENT_ID,
  OIDC_CLIENT_SECRET: process.env.OIDC_CLIENT_SECRET,
  OIDC_REDIRECT_URI: process.env.OIDC_REDIRECT_URI,
  API_HOST: process.env.API_HOST,
  API_BASEPATH: process.env.API_BASEPATH,
  BASE_PREFIX: process.env.BASE_PREFIX,
  PRIVATE_KEY_REDIS: process.env.PRIVATE_KEY_REDIS,
  PRIVATE_INIT_VECTOR: process.env.PRIVATE_INIT_VECTOR,
});
